# Generated by Django 4.1.5 on 2023-01-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=50)),
                ("firstname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("number", models.CharField(max_length=11)),
                ("pass1", models.CharField(max_length=500)),
                ("pass2", models.CharField(max_length=500)),
            ],
        ),
    ]
