# Generated by Django 4.1.5 on 2023-02-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="contact", name="pass1",),
        migrations.RemoveField(model_name="contact", name="pass2",),
    ]
