# Generated by Django 4.1.5 on 2023-02-26 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diet", "0003_contact_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailsN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diabetes_type", models.CharField(max_length=100)),
                ("weight", models.FloatField()),
                ("height", models.FloatField()),
                ("gender", models.CharField(max_length=50)),
                ("activity_level", models.CharField(max_length=500)),
                ("age", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
