# Generated by Django 4.1.5 on 2023-02-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0004_detailsn"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailsn",
            name="bmr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="detailsn",
            name="daily_calories",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
