# Generated by Django 4.1.7 on 2023-03-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_alter_detailsn_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsn',
            name='bmi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detailsn',
            name='pregnant',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
