# Generated by Django 4.1.7 on 2023-03-11 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0007_detailsn_bmi_detailsn_pregnant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCalorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carb_grams', models.CharField(max_length=100)),
                ('protein_grams', models.CharField(max_length=100)),
                ('fat_grams', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
