# Generated by Django 4.1.7 on 2023-03-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0009_foodlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodList',
        ),
    ]
