# Generated by Django 4.1.7 on 2023-03-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0011_foodlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsn',
            name='food_id',
            field=models.IntegerField(null=True),
        ),
    ]
