# Generated by Django 4.1.7 on 2023-03-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0012_detailsn_food_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsn',
            name='food_id',
        ),
        migrations.AddField(
            model_name='foodlist',
            name='food_id',
            field=models.IntegerField(null=True),
        ),
    ]
