# Generated by Django 4.1.7 on 2023-03-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0013_remove_detailsn_food_id_foodlist_food_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='food_id',
        ),
    ]
