# Generated by Django 4.1.7 on 2023-03-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0016_mealplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
