# Generated by Django 4.1.7 on 2023-03-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0017_delete_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='timezone',
            field=models.CharField(default='Africa/Lagos', max_length=100),
        ),
    ]
