# Generated by Django 4.1.7 on 2023-03-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0019_mealplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=11)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Thursday', max_length=10),
        ),
    ]
