# Generated by Django 4.1.7 on 2023-03-16 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0021_contactus2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs2',
        ),
    ]
