# Generated by Django 4.1.7 on 2023-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0024_doctors_alter_mealplan_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='breakfast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='dinner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='lunch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='snack',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
