# Generated by Django 4.1.7 on 2023-03-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0025_alter_mealplan_breakfast_alter_mealplan_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcalorie',
            name='meal_carb_gram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dcalorie',
            name='meal_fat_gram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dcalorie',
            name='meal_protein_gram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='breakfast_carb_gram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='breakfast_fat_gram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='breakfast_protein_gram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='dinner_carb_gram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='dinner_fat_gram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='dinner_protein_gram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='lunch_carb_gram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='lunch_fat_gram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='lunch_protein_gram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='snack_carb_gram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='snack_fat_gram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='snack_protein_gram',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
