# Generated by Django 4.1.5 on 2023-03-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0020_alter_mealplan_day'),
        ('diet', '0026_dcalorie_meal_carb_gram_dcalorie_meal_fat_gram_and_more'),
    ]

    operations = [
    ]
