# Generated by Django 4.1.5 on 2023-04-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0027_merge_20230328_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='breakfast_carb_gram',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='breakfast_fat_gram',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='breakfast_protein_gram',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='dinner_carb_gram',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='dinner_fat_gram',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='dinner_protein_gram',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='lunch_carb_gram',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='lunch_fat_gram',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='lunch_protein_gram',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='snack_carb_gram',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='snack_fat_gram',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='snack_protein_gram',
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='breakfast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_breakfast', to='diet.foodlist'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Thursday', max_length=10),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='dinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_dinner', to='diet.foodlist'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='lunch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_lunch', to='diet.foodlist'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='snack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_snack', to='diet.foodlist'),
        ),
    ]
