# Generated by Django 4.1.5 on 2023-04-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0028_remove_mealplan_breakfast_carb_gram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='week_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
