# Generated by Django 4.1.7 on 2023-04-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0029_alter_mealplan_week_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Sunday', max_length=10),
        ),
    ]
